/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const $globalGuard: typeof import('@/hooks/usePrompt')['$globalGuard']
  const $globalKeepRouter: typeof import('@/hooks/useKeepRouter')['$globalKeepRouter']
  const $globalLazy: typeof import('@/hooks/useKeepRouter')['$globalLazy']
  const $globalNavigate: typeof import('@/hooks/useCustomNavigate')['$globalNavigate']
  const $globalReady: typeof import('@/hooks/useInitialize')['$globalReady']
  const $globalRedux: typeof import('@/hooks/useRedux')['$globalRedux']
  const $globalReduxAction: typeof import('@/hooks/useRedux')['$globalReduxAction']
  const $globalRequest: typeof import('@/hooks/useFetch')['$globalRequest']
  const $globalRequestUrl: typeof import('@/hooks/useFetch')['$globalRequestUrl']
  const $globalRouter: typeof import('@/hooks/useLoadRouter')['$globalRouter']
  const $globalServicer: typeof import('@/hooks/useService')['$globalServicer']
  const Link: typeof import('react-router-dom')['Link']
  const NavLink: typeof import('react-router-dom')['NavLink']
  const Navigate: typeof import('react-router-dom')['Navigate']
  const Outlet: typeof import('react-router-dom')['Outlet']
  const Route: typeof import('react-router-dom')['Route']
  const Routes: typeof import('react-router-dom')['Routes']
  const useHref: typeof import('react-router-dom')['useHref']
  const useInRouterContext: typeof import('react-router-dom')['useInRouterContext']
  const useLinkClickHandler: typeof import('react-router-dom')['useLinkClickHandler']
  const useLocation: typeof import('react-router-dom')['useLocation']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useNavigationType: typeof import('react-router-dom')['useNavigationType']
  const useOutlet: typeof import('react-router-dom')['useOutlet']
  const useOutletContext: typeof import('react-router-dom')['useOutletContext']
  const useParams: typeof import('react-router-dom')['useParams']
  const useResolvedPath: typeof import('react-router-dom')['useResolvedPath']
  const useRoutes: typeof import('react-router-dom')['useRoutes']
  const useSearchParams: typeof import('react-router-dom')['useSearchParams']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
